apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ng-spot
spec:
  instanceProfile: "prod-karpenter-node-profile"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "sqs-job-prod"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "sqs-job-prod"
  tags:
    karpenter.sh/discovery: "sqs-job-prod"
    NodePool: ng-spot
